import { geminiCall } from '../../utils/geminiCall';
import { logger } from '../../utils/loggers';
import { generateQuizPrompt } from '../../utils/prompts/quiz-temp';
import { QuizRepository } from './repository';
import {
  type Quiz,
  type GenerateQuizRequest,
  type SubmitQuizRequest,
  type QuizAttempt,
  type QuizGenerationResponse,
  quizSchema,
} from './types';

export class QuizService {
  private quizRepository: QuizRepository;

  constructor(quizRepository?: QuizRepository) {
    this.quizRepository = quizRepository || new QuizRepository();
  }

  async generateQuiz(request: GenerateQuizRequest): Promise<Quiz> {
    try {
      logger.info(`Generating quiz for lesson: ${request.lessonId}`);

      const existingQuiz = await this.quizRepository.getQuizByLessonId(
        request.lessonId
      );
      if (existingQuiz) {
        logger.info(
          `Quiz already exists for lesson: ${request.lessonId}, returning existing quiz`
        );
        return existingQuiz;
      }

      const prompt = generateQuizPrompt({
        lessonName: request.lessonName,
        previousLessonsContent: request.previousLessonsContent,
        numberOfQuestions: request.numberOfQuestions || 5,
        difficulty: request.difficulty || 'medium',
      });

      logger.info('Calling Gemini API to generate quiz questions');
      const result: QuizGenerationResponse = await geminiCall(prompt, {
        responseSchema: quizSchema,
        temperature: 0.8,
        maxRetries: 3,
      });

      if (!result.questions || result.questions.length === 0) {
        throw new Error('No questions generated by Gemini');
      }

      logger.info(`Generated ${result.questions.length} questions for quiz`);

      const quiz = await this.quizRepository.createQuiz({
        lessonId: request.lessonId,
        questions: result.questions,
        passingScore: 70,
      });

      logger.info(`Quiz created successfully with id: ${quiz.id}`);
      return quiz;
    } catch (error) {
      logger.error('Error generating quiz:', error);
      throw error;
    }
  }

  async getQuiz(lessonId: string): Promise<Quiz | null> {
    try {
      logger.info(`Fetching quiz for lesson: ${lessonId}`);
      return await this.quizRepository.getQuizByLessonId(lessonId);
    } catch (error) {
      logger.error('Error fetching quiz:', error);
      throw error;
    }
  }

  async getQuizForStudent(lessonId: string): Promise<any> {
    try {
      logger.info(`Fetching quiz for student, lesson: ${lessonId}`);
      const quiz = await this.quizRepository.getQuizByLessonId(lessonId);

      if (!quiz) {
        return null;
      }

      return {
        id: quiz.id,
        lessonId: quiz.lessonId,
        passingScore: quiz.passingScore,
        questions: quiz.questions.map((q) => ({
          questionId: q.questionId,
          questionText: q.questionText,
          questionType: q.questionType,
          options: q.options,
          points: q.points,
        })),
      };
    } catch (error) {
      logger.error('Error fetching quiz for student:', error);
      throw error;
    }
  }

  async submitQuiz(
    userId: string,
    request: SubmitQuizRequest
  ): Promise<QuizAttempt> {
    try {
      logger.info(`User ${userId} submitting quiz ${request.quizId}`);

      const quiz = await this.quizRepository.getQuizById(request.quizId);
      if (!quiz) {
        throw new Error('Quiz not found');
      }

      const gradedAnswers = request.answers.map((answer) => {
        const question = quiz.questions.find(
          (q) => q.questionId === answer.questionId
        );
        if (!question) {
          throw new Error(`Question ${answer.questionId} not found`);
        }

        const isCorrect = answer.selectedAnswer === question.correctAnswer;
        return {
          questionId: answer.questionId,
          selectedAnswer: answer.selectedAnswer,
          isCorrect,
          correctAnswer: question.correctAnswer,
          explanation: question.explanation,
        };
      });

      const correctCount = gradedAnswers.filter((a) => a.isCorrect).length;
      const score = Math.round((correctCount / quiz.questions.length) * 100);
      const passed = score >= quiz.passingScore;

      logger.info(
        `Quiz graded: ${correctCount}/${quiz.questions.length} correct, score: ${score}%, passed: ${passed}`
      );

      const attempt = await this.quizRepository.saveAttempt({
        userId,
        lessonId: quiz.lessonId,
        quizId: request.quizId,
        answers: gradedAnswers,
        score,
        passed,
        startedAt: new Date(),
        completedAt: new Date(),
      });

      logger.info(`Quiz attempt saved with id: ${attempt.id}`);
      return attempt;
    } catch (error) {
      logger.error('Error submitting quiz:', error);
      throw error;
    }
  }

  async getUserAttempts(
    userId: string,
    quizId: string
  ): Promise<QuizAttempt[]> {
    try {
      logger.info(`Fetching attempts for user: ${userId}, quiz: ${quizId}`);
      return await this.quizRepository.getUserAttempts(userId, quizId);
    } catch (error) {
      logger.error('Error fetching user attempts:', error);
      throw error;
    }
  }

  async getAttemptById(attemptId: string): Promise<QuizAttempt | null> {
    try {
      logger.info(`Fetching attempt with id: ${attemptId}`);
      return await this.quizRepository.getAttemptById(attemptId);
    } catch (error) {
      logger.error('Error fetching attempt:', error);
      throw error;
    }
  }
}
